id = "varnish"
name = "Varnish"
version = "0.0.1"
schema_version = 1
authors = ["Herjuus <me@herjus.no>"]
description = "Language support for Varnish."
repository = "https://github.com/herjuus/zed-vcl"
