id = "varnish"
name = "Varnish"
version = "0.0.1"
schema_version = 1
authors = ["Herjuus <me@herjus.no>"]
description = "Language support for Varnish."
repository = "https://github.com/herjuus/zed-vcl"

[language_servers.varnishls]
name = "Varnish Language Server"
languages = ["Varnish vcl", "Varnish vtc"]
language_ids = { "Varnish vcl" = "varnish-vcl", "Varnish vtc" = "varnish-vtc" }
code_action_kinds = []
